apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: api-server
  name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - command:
        - flask
        - run
        - --host=0.0.0.0
        env:
        - name: FLASK_APP
          value: api-server.py
        - name: REDIS_HOST
          value: redis
        image: briandeheus/api-server:v1
        name: api-server
