apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: event-worker
  name: event-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-worker
  template:
    metadata:
      labels:
        app: event-worker
    spec:
      containers:
      - command:
        - python
        - event-worker.py
        env:
        - name: REDIS_HOST
          value: redis
        image: briandeheus/event-worker:v1
        name: api-server
